
spring:

  application:
    name: onetoone-lazy
  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
#        enable_lazy_load_no_trans: false
        # enhancer:
        #   enableLazyInitialization: true
        #   enableDirtyTracking: true
        #   enableAssociationManagement: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE  # 파라미터 바인딩 값
    # org.hibernate.orm.jdbc.extract: TRACE  # (선택) ResultSet 추출 로그


server:
  port: 8899
